// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using MortgageApp;
using System;

namespace MortgageApp.Migrations
{
    [DbContext(typeof(MortgageContext))]
    partial class MortgageContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MortgageApp.Models.Mortgage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("DownPayment");

                    b.Property<decimal>("Dues");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<decimal>("Pmi");

                    b.Property<decimal>("PropertyTax");

                    b.Property<decimal>("PurchasePrice");

                    b.Property<decimal>("Rate");

                    b.Property<decimal>("Term");

                    b.HasKey("Id");

                    b.ToTable("Mortgages");
                });
#pragma warning restore 612, 618
        }
    }
}
